CREATE TABLE `system_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`uiTheme` enum('system','light','dark') NOT NULL DEFAULT 'system',
	`accentColor` varchar(32) DEFAULT 'violet',
	`fontScale` enum('small','medium','large') NOT NULL DEFAULT 'medium',
	`reducedMotion` boolean NOT NULL DEFAULT false,
	`sidebarCollapsed` boolean NOT NULL DEFAULT false,
	`analyticsConsent` boolean NOT NULL DEFAULT false,
	`crashReportConsent` boolean NOT NULL DEFAULT false,
	`shareUsageData` boolean NOT NULL DEFAULT false,
	`showProfilePublicly` boolean NOT NULL DEFAULT false,
	`autoBackupEnabled` boolean NOT NULL DEFAULT true,
	`backupFrequency` enum('daily','weekly','monthly') NOT NULL DEFAULT 'weekly',
	`backupRetentionDays` int NOT NULL DEFAULT 30,
	`lastBackupAt` timestamp,
	`defaultModality` enum('image','video','audio','voice') NOT NULL DEFAULT 'image',
	`defaultCreativeMode` enum('balanced','creative','precise') NOT NULL DEFAULT 'balanced',
	`autoSaveHistory` boolean NOT NULL DEFAULT true,
	`nsfwFilter` boolean NOT NULL DEFAULT true,
	`emailNotifications` boolean NOT NULL DEFAULT true,
	`generationCompleteNotify` boolean NOT NULL DEFAULT true,
	`weeklyDigestEnabled` boolean NOT NULL DEFAULT false,
	`locale` varchar(16) DEFAULT 'zh-TW',
	`timezone` varchar(64) DEFAULT 'Asia/Taipei',
	`extraSettings` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `system_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `system_settings_userId_unique` UNIQUE(`userId`)
);
