CREATE TABLE `custom_blocks_combo` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`modality` enum('image','video','audio','voice') NOT NULL,
	`subjectBlock` json,
	`styleBlock` json,
	`lightingBlock` json,
	`cameraBlock` json,
	`moodBlock` json,
	`extraBlocks` json,
	`vibeCardIds` json,
	`freeformPrompt` text,
	`negativePrompt` text,
	`compiledPrompt` text,
	`parameterSnapshot` json,
	`brainConfigSnapshot` json,
	`previewImageUrl` text,
	`isCurated` boolean NOT NULL DEFAULT false,
	`isPublic` boolean NOT NULL DEFAULT false,
	`forkCount` int NOT NULL DEFAULT 0,
	`likeCount` int NOT NULL DEFAULT 0,
	`useCount` int NOT NULL DEFAULT 0,
	`tags` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `custom_blocks_combo_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_ai_brain` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`directorModel` varchar(128) NOT NULL DEFAULT 'gpt-4o',
	`directorTemperature` decimal(3,2) NOT NULL DEFAULT '0.7',
	`directorTopP` decimal(3,2) NOT NULL DEFAULT '0.9',
	`directorSystemPrompt` text,
	`directorEnabled` boolean NOT NULL DEFAULT true,
	`analystModel` varchar(128) NOT NULL DEFAULT 'gpt-4o',
	`analystTemperature` decimal(3,2) NOT NULL DEFAULT '0.3',
	`analystTopP` decimal(3,2) NOT NULL DEFAULT '0.8',
	`analystSystemPrompt` text,
	`analystEnabled` boolean NOT NULL DEFAULT true,
	`storytellerModel` varchar(128) NOT NULL DEFAULT 'gpt-4o',
	`storytellerTemperature` decimal(3,2) NOT NULL DEFAULT '0.9',
	`storytellerTopP` decimal(3,2) NOT NULL DEFAULT '0.95',
	`storytellerSystemPrompt` text,
	`storytellerEnabled` boolean NOT NULL DEFAULT true,
	`technicianModel` varchar(128) NOT NULL DEFAULT 'gpt-4o',
	`technicianTemperature` decimal(3,2) NOT NULL DEFAULT '0.2',
	`technicianTopP` decimal(3,2) NOT NULL DEFAULT '0.7',
	`technicianSystemPrompt` text,
	`technicianEnabled` boolean NOT NULL DEFAULT true,
	`curatorModel` varchar(128) NOT NULL DEFAULT 'gpt-4o',
	`curatorTemperature` decimal(3,2) NOT NULL DEFAULT '0.8',
	`curatorTopP` decimal(3,2) NOT NULL DEFAULT '0.9',
	`curatorSystemPrompt` text,
	`curatorEnabled` boolean NOT NULL DEFAULT true,
	`imageEngine` varchar(128) NOT NULL DEFAULT 'flux-pro',
	`imageEngineParams` json,
	`imageEngineEnabled` boolean NOT NULL DEFAULT true,
	`videoEngine` varchar(128) NOT NULL DEFAULT 'kling-v1',
	`videoEngineParams` json,
	`videoEngineEnabled` boolean NOT NULL DEFAULT true,
	`audioEngine` varchar(128) NOT NULL DEFAULT 'suno-v4',
	`audioEngineParams` json,
	`audioEngineEnabled` boolean NOT NULL DEFAULT true,
	`voiceEngine` varchar(128) NOT NULL DEFAULT 'elevenlabs-v2',
	`voiceEngineParams` json,
	`voiceEngineEnabled` boolean NOT NULL DEFAULT true,
	`globalPreferences` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_ai_brain_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_ai_brain_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `user_model_switch_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`brainSlot` enum('director','analyst','storyteller','technician','curator','imageEngine','videoEngine','audioEngine','voiceEngine') NOT NULL,
	`fromModel` varchar(128) NOT NULL,
	`toModel` varchar(128) NOT NULL,
	`fromParams` json,
	`toParams` json,
	`reason` text,
	`switchSource` enum('manual','soul_recommendation','auto_fallback','ab_test') NOT NULL DEFAULT 'manual',
	`switchedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `user_model_switch_logs_id` PRIMARY KEY(`id`)
);
