ALTER TABLE `agent_preferences`
ADD COLUMN IF NOT EXISTS `preferredSpecialistAgent` VARCHAR(64) NULL,
ADD COLUMN IF NOT EXISTS `specialistAutoActivate` BOOLEAN DEFAULT TRUE NOT NULL,
ADD COLUMN IF NOT EXISTS `specialistProactiveMode` BOOLEAN DEFAULT TRUE NOT NULL,
ADD COLUMN IF NOT EXISTS `specialistLearningEnabled` BOOLEAN DEFAULT TRUE NOT NULL,
ADD COLUMN IF NOT EXISTS `disabledSpecialistAgents` JSON NOT NULL DEFAULT ('[]');
