export {
  APP_PAGE_REGISTRY,
  SIDEBAR_GROUPS,
  getAgentHomeEntries,
  getAllPages,
  getDockPages,
  getPageById,
  getPageByPath,
  getSidebarGroups,
  getSidebarPages,
  getSidebarTree,
  serializeRegistryForSiteKnowledge,
  type AppPageGroupId,
  type AppPageQuickAction,
  type AppPageRegistryItem,
  type SerializableAppRegistryItem,
  type SidebarGroupDefinition,
  type SidebarGroupId,
  type SidebarTreeBranch,
  type SidebarTreeLeaf,
  type SidebarTreeNode,
} from "../../../shared/appRegistry";
